# Generated by Django 4.0.4 on 2022-04-20 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='comment',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
